"""initial semantic memory schema

Revision ID: bbde382265cb
Revises: 
Create Date: 2026-09-10 14:39:51.849629
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = 'bbde382265cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('memories',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=100), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('predicate', sa.String(length=200), nullable=False),
    sa.Column('object_value', sa.Text(), nullable=False),
    sa.Column('epistemic_status', sa.String(length=30), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=30), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_method', sa.String(length=100), nullable=False),
    sa.Column('extraction_model', sa.String(length=200), nullable=True),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('supersedes_memory_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['supersedes_memory_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_project_id'), 'memories', ['project_id'], unique=False)
    op.create_index('ix_memories_project_lifecycle', 'memories', ['project_id', 'lifecycle_status'], unique=False)
    op.create_table('query_runs',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=100), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('candidate_memory_ids', sqlite.JSON(), nullable=False),
    sa.Column('selected_memory_ids', sqlite.JSON(), nullable=False),
    sa.Column('retrieval_latency_ms', sa.Integer(), nullable=False),
    sa.Column('end_to_end_latency_ms', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_runs_project_id'), 'query_runs', ['project_id'], unique=False)
    op.create_table('takes',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=100), nullable=True),
    sa.Column('raw_asr', sa.Text(), nullable=True),
    sa.Column('formatted_text', sa.Text(), nullable=True),
    sa.Column('source_application', sa.String(length=100), nullable=False),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_metadata', sqlite.JSON(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tombstoned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_takes_project_id'), 'takes', ['project_id'], unique=False)
    op.create_table('memory_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('memory_id', sa.String(length=100), nullable=False),
    sa.Column('take_id', sa.String(length=100), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('evidence_role', sa.String(length=50), nullable=False),
    sa.Column('sufficiency_contribution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['take_id'], ['takes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id', 'take_id', 'span_start', 'span_end', name='uq_memory_evidence_span')
    )
    op.create_index(op.f('ix_memory_evidence_memory_id'), 'memory_evidence', ['memory_id'], unique=False)
    op.create_index(op.f('ix_memory_evidence_take_id'), 'memory_evidence', ['take_id'], unique=False)
    op.create_table('query_claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_run_id', sa.String(length=100), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('memory_ids', sqlite.JSON(), nullable=False),
    sa.Column('supporting_take_ids', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['query_run_id'], ['query_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_claims_query_run_id'), 'query_claims', ['query_run_id'], unique=False)
    op.create_table('tombstones',
    sa.Column('take_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purge_status', sa.String(length=20), nullable=False),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['take_id'], ['takes.id'], ),
    sa.PrimaryKeyConstraint('take_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tombstones')
    op.drop_index(op.f('ix_query_claims_query_run_id'), table_name='query_claims')
    op.drop_table('query_claims')
    op.drop_index(op.f('ix_memory_evidence_take_id'), table_name='memory_evidence')
    op.drop_index(op.f('ix_memory_evidence_memory_id'), table_name='memory_evidence')
    op.drop_table('memory_evidence')
    op.drop_index(op.f('ix_takes_project_id'), table_name='takes')
    op.drop_table('takes')
    op.drop_index(op.f('ix_query_runs_project_id'), table_name='query_runs')
    op.drop_table('query_runs')
    op.drop_index('ix_memories_project_lifecycle', table_name='memories')
    op.drop_index(op.f('ix_memories_project_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_table('projects')
    # ### end Alembic commands ###

